array access for boolean
private-attribution/ipa pull request #1067
Opened 2024-05-14 19:08 UTC by bmcase

small PR to implement ArrayAccess trait for Boolean.  Have run into needing when working on DP noise in MPC but probably not bad to have it generally added.   w/ @akoshelev

2024-05-14 20:01 UTC, akoshelev commented
this change makes sense to me, although I agree with Coverlay - it would be nice to add tests

2024-05-14 21:04 UTC, bmcase commented
added tests

2024-05-14 21:13 UTC, akoshelev approved these changes

2024-05-14 21:13 UTC, akoshelev commented on ipa-core/src/ff/boolean.rs
> +        assert_eq!(count, 1);
```suggestion
        assert_eq(vec![Boolean::from(false)], b.iter().collect::<Vec<_>>());
```

2024-05-14 21:59 UTC, bmcase commented
@akoshelev  finished updating the suggested change.

2024-05-15 00:27 UTC, benjaminsavage requested changes
I think @andyleiserson very intentionally did not add support for ArrayAccess. Idea being that people will likely get it wrong and/or do something super intefficient.

Usually, you should be able to use `transpose` to construct these things.

2024-05-15 16:51 UTC, bmcase commented
This PR was to part of building DP noise in MPC without vectorization.  But I see that other recent changes have also removed non-vectorized usage for functions like `integer_add` that I was starting to use.  So it may be best to scrap this approach and just start directly on implementing DP noise in MPC with vectorization if that is what all the underlying code is moving towards. 

I'll chat with Andy later and see what he thinks and get some direction to start on the vectorized approach.

2024-05-15 18:22 UTC, andyleiserson approved these changes
This seems reasonable to me, as a way of making the boolean array APIs scale down to a width of 1.

> I think @andyleiserson very intentionally did not add support for ArrayAccess.

That was in the context of vectorized shares -- `AdditiveShare<Boolean, N>`. The boolean array types do implement array access, and if you view `Boolean` as `BA1`, then it seems reasonable for it to support the same APIs as the larger arrays.

However, not seeing the broader context where this will be used, I can't say for sure that it seems like the right API for the task.

> I see that other recent changes have also removed non-vectorized usage for functions like integer_add that I was starting to use

It should still be possible to invoke an unvectorized `integer_add`, using `BitDecomposed<AdditiveShare<Boolean>>` rather than `AdditiveShare<BA{n}>`. It will be less efficient, but if efficiency is a dominant concern, then vectorization is they way to go.

2024-05-15 18:22 UTC, andyleiserson commented on ipa-core/src/ff/boolean.rs
> +        debug_assert!(index < 1);
In isolation, a debug_assert seems reasonable here. On the other hand, out-of-bounds array indexing will normally panic even in release builds. I'm not sure which way makes more sense here.

2024-05-19 05:14 UTC, benjaminsavage approved these changes
If andy is happy then I'm happy :). Shall we merge it?

2024-05-21 06:22 UTC, merged