num_bernoulli from epsilon, delta
private-attribution/ipa pull request #1113
Opened 2024-06-04 00:30 UTC by bmcase

Small PR to implement Thm 1 of this paper https://arxiv.org/pdf/1805.10559 which allows us to go from an epsilon, delta and other parameters to the minimum number of bernoulli samples we need to achieve that level of DP.
See this doc for more discussion. https://docs.google.com/document/d/116qQIgVoz3uV8axbmVWfif6dTjBVww5THecPqC0kERw/edit
Much of this PR is a translation into Rust of this earlier python script https://github.com/private-attribution/ipa/compare/main...bmcase:raw-ipa:binomial_variable_p

2024-06-04 05:32 UTC, benjaminsavage commented on ipa-core/src/protocol/ipa_prf/dp/mod.rs
> +    for num_bernoulli in 1..10_000_000 {
Woah... seriously?

Surely we can at least do a binary search?

2024-06-04 05:39 UTC, benjaminsavage requested changes
Looping over 10 million is just too inefficient. Please convert to a binary search.

2024-06-04 16:07 UTC, bmcase commented
@benjaminsavage  converted to binary search for finding the smallest num_beroulli.

2024-06-05 05:46 UTC, benjaminsavage approved these changes

2024-06-05 05:46 UTC, merged