keep track of amount of u,v values included in a proof
private-attribution/ipa pull request #1143
Opened 2024-06-15 00:51 UTC by danielmasny

This PR allows to keep track of amount of u,v values when generate proof. This is important since the verification will need to know the amount.

2024-06-15 06:05 UTC, benjaminsavage requested changes
I disagree with this design. I do not think compute proof should be responsible for counting the elements added to it. Look at all the complex tuple return types and the frequently ignored values. This is not a good design. 

I think when we perform a multiplication and push it into the list of multiplications that need to be verified, THAT is the place to increment a counter. In fact, it's only that first stage where we need to perform this count.

2024-06-17 16:42 UTC, danielmasny commented
> I disagree with this design. I do not think compute proof should be responsible for counting the elements added to it. Look at all the complex tuple return types and the frequently ignored values. This is not a good design.
> 
> I think when we perform a multiplication and push it into the list of multiplications that need to be verified, THAT is the place to increment a counter. In fact, it's only that first stage where we need to perform this count.

@benjaminsavage I would be fine with that too and was thinking about that as well. A reason why I think this PR is more straightforward is that we just count the amount when we actually compute the proof (which will be the same for all three proofs and doesn't need to be sent over the network). Counting the multiplications when they are stored comes with two challenges:
- We collect the multiplication in a hash table so we would need to keep track of the number in each element of the hash table
- There might be zero fillings that we need to account for.

2024-06-20 10:29 UTC, benjaminsavage requested changes
I still remain convinced this is the wrong design. I'm waiting for an update to this PR, or perhaps a new PR that approaches this differently.

2024-06-20 10:29 UTC, benjaminsavage commented on ipa-core/src/protocol/ipa_prf/malicious_security/prover.rs
> +    /// returns proof and number of summands `m` which is important for the verification
Generally, when you find yourself writing that a function does X *and* Y, it should be two separate functions.

2024-06-20 10:29 UTC, benjaminsavage commented on ipa-core/src/protocol/ipa_prf/malicious_security/prover.rs
> +        uv_iterator: J,
If this implemented "ExactSizeIterator" we would be done. There would be no need for this. Can we do that instead?

2024-06-20 10:29 UTC, benjaminsavage commented on ipa-core/src/protocol/ipa_prf/malicious_security/prover.rs
> +        let (proof_2, _) = TestProofGenerator::compute_proof(uv_2.iter(), &lagrange_table);
To me, this line makes it so clear that this is the wrong design. We call `compute_proof` multiple times, but we only care about the size of the iterator we pass to it on the first iteration. Surely we should just treat that first iteration differently (e.g. add this counter to either the storage of multiplications to be validated, or possibly to the one-time conversion from binary to large field values).

2024-06-20 10:29 UTC, benjaminsavage commented on ipa-core/src/protocol/ipa_prf/malicious_security/prover.rs
> +        let (proof_3, _) = TestProofGenerator::compute_proof(masked_uv_3.iter(), &lagrange_table);
And here we ignore it again.

2024-06-22 05:35 UTC, benjaminsavage approved these changes

2024-06-22 05:59 UTC, merged