Fix the DP wrapping-add attack
private-attribution/ipa pull request #589
Opened 2023-04-12 05:34 UTC by taikiy

This PR fixes the issue #520.

2023-04-12 17:06 UTC, akoshelev requested changes
all good, we should consider returning an error if cap > PRIME / 2 to avoid server crash on bad client inputs.

2023-04-13 03:32 UTC, taikiy commented on src/protocol/ipa/mod.rs
> +        assert_eq!(count, 1);
Much cleaner. Thanks!

2023-04-13 04:03 UTC, taikiy commented on src/protocol/attribution/credit_capping.rs
> +    if (u128::from(cap) * 2) >= F::PRIME.into() {
Cast `cap:u32` to u128 first and then multiply by 2 to avoid overflow.

2023-04-18 07:49 UTC, benjaminsavage commented on src/protocol/attribution/credit_capping.rs
> +/// ## Panics
I'm not sure if we should panic *here*. This seems like something that we would ideally validate at the very beginning of the protocol, not delay until after we have done a bunch of work (like sorting).

2023-04-18 07:51 UTC, benjaminsavage commented on src/protocol/attribution/credit_capping.rs
> +async fn report_level_capping<F, C, T>(
I would really appreciate a comment that explains how this fixes the root issue we are concerned about. I don't understand it right now.

2023-04-19 08:00 UTC, benjaminsavage commented on src/protocol/attribution/credit_capping.rs
> +            "The cap {cap} must be less than 1/2 of the prime number to avoid overflow.",
Technically, this does not prevent overflow. We can still have it, but it becomes detectable. Perhaps:

```
The cap {cap} must be less than 1/2 of the prime modulus to make overflow detectable, and propagable.
```

2023-04-19 08:02 UTC, benjaminsavage commented on src/protocol/attribution/credit_capping.rs
>      // We compute capped credits in the method, and writes to `original_credits`.
I think the comment is out of date.

2023-04-19 08:38 UTC, benjaminsavage commented on src/protocol/attribution/credit_capping.rs
> +async fn report_level_capping<F, C, T>(
This comment is good. I think it would probably be better above:

```
pub async fn credit_capping<F, C, T>(
```

2023-04-19 08:42 UTC, benjaminsavage commented on src/protocol/attribution/credit_capping.rs
> +async fn comp_bits_prefix_or<F, C, T>(
I don't love this name. What is "comb" short for?

2023-04-19 08:43 UTC, benjaminsavage commented on src/protocol/attribution/credit_capping.rs
> +async fn comp_bits_prefix_or<F, C, T>(
Could we call it something like "propagate_overflow_detection"?

2023-04-19 08:50 UTC, benjaminsavage commented on src/protocol/ipa/mod.rs
> +        //   * the credit is attributed to at most one breakdown key.
I don't understand this part. Why would we need to require this? And where is the code that guarantees this?

2023-04-19 08:51 UTC, benjaminsavage commented on src/protocol/ipa/mod.rs
> +        const RECORDS_SENT_SEMI_HONEST_BASELINE_CAP_3: u64 = 21_936;
20% increase =(

2023-04-19 08:52 UTC, benjaminsavage commented on src/protocol/ipa/mod.rs
> +        const BYTES_SENT_SEMI_HONEST_BASELINE_CAP_3: u64 = 78_456;
23% increase =(

2023-04-19 08:52 UTC, benjaminsavage commented on src/protocol/ipa/mod.rs
> +        const BYTES_SENT_MALICIOUS_BASELINE_CAP_3: u64 = 212_472;
21.6% increase =(

Who knew fixing a bug would be so expensive =(

2023-04-19 10:26 UTC, benjaminsavage commented on src/protocol/attribution/mod.rs
> +    should_add_on_first_iteration: bool,
OK, I think I understand this now, but it's poorly documented (my fault, not yours). I think we should address this with a comment.

```
/// If the caller has foreknowledge that there will never be any two adjacent rows, *both* containing a 1, then it is same to pass `true`, which will simply add values on the first iteration (thereby saving one multiplication per row). If the caller does not know of any such guarantee, `false` should be passed.

2023-04-19 10:33 UTC, benjaminsavage approved these changes
Thanks for fixing this bug @taikiy!

2023-04-19 10:52 UTC, merged